#
# instructions tbd.
#
TYPO3:
  Flow:
    persistence:
      backendOptions:
        dbname: 'sphere_neos_demo'
        user: 'root'
        password: 'password'
Sphere:
  Neos:
    client:
      clientId: 'your client id'
      clientSecret: 'your client secret'
      project: 'your-project-name'
