#
# instructions tbd.
#
Sphere:
  Neos:
    client:
      clientId: 'your client id'
      clientSecret: 'your client secret'
      project: 'your-project-name'
    project:
      currency: 'EUR'
      country: 'DE'
